default_context:
  _pegasus_version: '2024.8'
  ai_chat_mode: none
  ai_image_mode: none
  author_name: Daniel Mouris
  ci: github_actions
  css_framework: tailwind
  css_theme: default
  database: postgres
  deploy_platform: none
  description: ZonPrepsOc
  docker_setup: default
  domain_name: localhost:8000
  email: dgmouris@gmail.com
  enable_github_login: n
  enable_google_login: n
  enable_twitter_login: n
  front_end_framework: react
  include_static_files: y
  marketing_email_platform: none
  post_process: y
  project_name: ZonPrep OCR Parser.
  project_slug: zon_prep_ocr_project
  standalone_front_end: none
  stripe_payment_mode: checkout
  subscription_billing_model: default
  subscription_pricing_ui: in_app
  use_2fa: y
  use_admin_docs: y
  use_api_auth: n
  use_api_keys: y
  use_async_example: n
  use_cloud_media_storage: n
  use_debug_toolbar: n
  use_docker: n
  use_ecommerce_example: n
  use_examples: n
  use_health_checks: n
  use_impersonation: y
  use_sentry: n
  use_subscriptions: n
  use_teams: n
  use_teams_example: n
  use_translations: y
  use_wagtail: n
