service: zon_prep_ocr_project

image: developmentzonprep/zon_prep_ocr_project

env:
  # This is the minimal set of environment variables needed to run the app
  # in production. You can add more here and in the .env file as needed.
  clear:
    DJANGO_SETTINGS_MODULE: zon_prep_ocr_project.settings_production
  secret:
    - POSTGRES_PASSWORD
    - SECRET_KEY
    - DATABASE_URL
    - REDIS_URL
    - CLOUD_STORAGE_CREDENTIALS
    - CLOUD_STORAGE_NAME
    - EMAIL_HOST_USER
    - EMAIL_HOST_USER_ALIAS
    - EMAIL_HOST_PASSWORD
    - SENDGRID_API_KEY
    - SEND_GRID_SENDER
    - EASYOCR_MODULE_PATH
    - SALESFORCE_USERNAME
    - SALESFORCE_PASSWORD
    - SALESFORCE_SECURITY_TOKEN
    - TURNSTILE_KEY
    - TURNSTILE_SECRET

# https://kamal-deploy.org/docs/configuration#using-different-roles-for-servers
servers:
  web:
    hosts:
      # - 35.188.245.231 # zonprep-server-1
      # - 35.245.129.206 # zonprep-production-2-easyocr
      - 34.21.37.212 # zonprep-production-3-easyocr
    options:
      expose: "8000"
      network: zon_prep_ocr_project-network
    labels:
      traefik.http.routers.zon_prep_ocr_project.rule: Host(`testing-zonprep.dgmouris.com`)
      traefik.http.routers.zon_prep_ocr_project_secure.entrypoints: websecure
      traefik.http.routers.zon_prep_ocr_project_secure.rule: Host(`testing-zonprep.dgmouris.com`)
      traefik.http.routers.zon_prep_ocr_project_secure.tls: true
      traefik.http.routers.zon_prep_ocr_project_secure.tls.certresolver: letsencrypt
  celery:
    hosts:
      # - 35.188.245.231 # zonprep-server-1
      # - 35.245.129.206 # zonprep-production-2-easyocr
      - 34.21.37.212 # zonprep-production-3-easyocr
    cmd: celery -A zon_prep_ocr_project worker --loglevel=INFO --concurrency=1 -Q email_queue,parsing_queue
    options:
      network: zon_prep_ocr_project-network
    labels:
      traefik.enable: "false"
  celerybeat:
    hosts:
      # - 35.188.245.231 # zonprep-server-1
      # - 35.245.129.206 # zonprep-production-2-easyocr
      - 34.21.37.212 # zonprep-production-3-easyocr
    cmd: celery -A zon_prep_ocr_project beat -l INFO
    options:
      network: zon_prep_ocr_project-network
    labels:
      traefik.enable: "false"

# https://kamal-deploy.org/docs/configuration#using-a-custom-healthcheck
healthcheck:
  path: /
  port: 8000
  max_attempts: 15
  interval: 20s

# To use a non-root user see https://kamal-deploy.org/docs/configuration#using-a-different-ssh-user-than-root
ssh:
  user: kamal

# https://kamal-deploy.org/docs/configuration#using-a-different-dockerfile-or-context-when-building
# Set multiarch to false for better performance if you are building your image on the same architecture as your server
builder:
  multiarch: true
  dockerfile: '../Dockerfile.web'
  context: '../'
  secrets:
    - CLOUD_STORAGE_CREDENTIALS
    - CLOUD_STORAGE_NAME
    - EMAIL_HOST_USER
    - EMAIL_HOST_PASSWORD
    - EASYOCR_MODULE_PATH
    - SENDGRID_API_KEY
    - SALESFORCE_USERNAME
    - SALESFORCE_PASSWORD

# See https://kamal-deploy.org/docs/configuration#using-another-registry-than-docker-hub
registry:
  username: developmentzonprep
  password:
    - KAMAL_REGISTRY_PASSWORD

accessories:
  # Note: Removed the database because it's going to be using
  # an external service take a look at the env to see the connection string.
  # docker hostname will be 'zon_prep_ocr_project-redis'
  redis:
    image: redis
    # host: 35.188.245.231 # zonprep-production-2-easyocr
    # host: 35.245.129.206 # zonprep-production-2-easyocr
    host: 34.21.37.212 # zonprep-production-3-easyocr
    options:
      network: zon_prep_ocr_project-network

traefik:
  options:
    network: zon_prep_ocr_project-network
    publish:
      - 443:443
    volume:
      - "/letsencrypt/acme.json:/letsencrypt/acme.json"
  args:
    entryPoints.web.address: ":80"
    entryPoints.websecure.address: ":443"
    certificatesResolvers.letsencrypt.acme.email: "development@zonprep.com"
    certificatesResolvers.letsencrypt.acme.storage: "/letsencrypt/acme.json"
    certificatesResolvers.letsencrypt.acme.httpchallenge: true
    certificatesResolvers.letsencrypt.acme.httpchallenge.entrypoint: web
