# Generated by Django 5.0.8 on 2024-08-12 16:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zonprep_file_parsing", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="zonprepappointment",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="zonprepappointment",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
