# Generated by Django 5.0.8 on 2024-08-12 21:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("zonprep_file_parsing", "0004_remove_externalfulfillmentemail_site_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="externalfulfillmentemail",
            old_name="contact_email",
            new_name="email",
        ),
    ]
