# Generated by Django 5.0.8 on 2024-08-13 21:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "zonprep_file_parsing",
            "0005_rename_contact_email_externalfulfillmentemail_email",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="zonprepappointment",
            name="raw_attachment_download",
            field=models.FileField(
                blank=True, null=True, upload_to="zonprep_appointment_attachments/"
            ),
        ),
    ]
