# Generated by Django 5.0.8 on 2024-08-13 22:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zonprep_file_parsing", "0006_zonprepappointment_raw_attachment_download"),
    ]

    operations = [
        migrations.AddField(
            model_name="zonprepappointment",
            name="raw_parsed_attachment_json_field",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
