# Generated by Django 5.0.8 on 2024-08-13 22:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "zonprep_file_parsing",
            "0007_zonprepappointment_raw_parsed_attachment_json_field",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="zonprepappointment",
            name="p_appointment_date",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="zonprepappointment",
            name="p_appointment_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="zonprepappointment",
            name="p_appointment_type",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="zonprepappointment",
            name="p_carrier",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="zonprepappointment",
            name="p_carrier_request_delivery_date",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="zonprepappointment",
            name="p_cartons",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="zonprepappointment",
            name="p_dock_door",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="zonprepappointment",
            name="p_freight_terms",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="zonprepappointment",
            name="p_pallets",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="zonprepappointment",
            name="p_percent_needed",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="zonprepappointment",
            name="p_priority_type",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="zonprepappointment",
            name="p_trailer_number",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="zonprepappointment",
            name="p_truck_location",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="zonprepappointment",
            name="p_units",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
