# Generated by Django 5.0.8 on 2024-08-15 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zonprep_file_parsing", "0008_zonprepappointment_p_appointment_date_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ZonprepPurchaseOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("state", models.CharField(max_length=255)),
                (
                    "p_shipment_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("P_pallets", models.CharField(blank=True, max_length=255, null=True)),
                ("p_cartons", models.CharField(blank=True, max_length=255, null=True)),
                ("p_units", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "p_po_number",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("p_pro", models.CharField(blank=True, max_length=255, null=True)),
                ("p_bols", models.CharField(blank=True, max_length=255, null=True)),
                ("p_asn", models.CharField(blank=True, max_length=255, null=True)),
                ("p_arn", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "p_freight_terms",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("p_vendor", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "p_shipment_label",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "appointment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="purchase_orders",
                        to="zonprep_file_parsing.zonprepappointment",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
