# Generated by Django 5.0.8 on 2024-08-19 19:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zonprep_file_parsing", "0012_zonprepappointmenttask"),
    ]

    operations = [
        migrations.CreateModel(
            name="GmailTokenCredentials",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("secret_credentials", models.JSONField(blank=True, null=True)),
                ("token", models.JSONField(blank=True, null=True)),
                ("gmail_user_id", models.CharField(max_length=255)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
