# Generated by Django 5.0.8 on 2024-08-28 21:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("zonprep_file_parsing", "0013_gmailtokencredentials"),
    ]

    operations = [
        migrations.RenameField(
            model_name="zonprepappointment",
            old_name="appointment_id",
            new_name="request_id",
        ),
    ]
