# Generated by Django 5.0.8 on 2024-09-16 15:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "zonprep_file_parsing",
            "0016_zonprepappointment_message_send_retried_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="zonprepappointment",
            name="p_scac",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
