# Generated by Django 5.0.8 on 2024-09-16 15:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zonprep_file_parsing", "0017_zonprepappointment_p_scac"),
    ]

    operations = [
        migrations.AddField(
            model_name="zonprepappointment",
            name="fc_code",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
