# Generated by Django 5.0.8 on 2024-10-04 16:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zonprep_file_parsing", "0018_zonprepappointment_fc_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="zonprepappointment",
            name="p_actual_arrival_date",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
