# Generated by Django 5.0.8 on 2024-10-30 23:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "zonprep_file_parsing",
            "0020_zonpreppurchaseorder_raw_parsed_attachment_json_field_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="zonpreppurchaseordersku",
            name="p_all_prep_details",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
