# Generated by Django 5.0.8 on 2024-12-09 23:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zonprep_file_parsing", "0022_zonprepreports"),
    ]

    operations = [
        migrations.CreateModel(
            name="TypeCEmailDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email_subject", models.CharField(max_length=255)),
                ("email_body", models.TextField()),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
