# Generated by Django 5.0.8 on 2025-01-02 23:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zonprep_file_parsing", "0023_typecemaildetails"),
    ]

    operations = [
        migrations.CreateModel(
            name="PauseEmailQueue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("paused", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AlterField(
            model_name="typecemaildetails",
            name="email_body",
            field=models.TextField(
                default="Need Shipment Prep Summary Request for PO_NUMBER"
            ),
        ),
        migrations.AlterField(
            model_name="typecemaildetails",
            name="email_subject",
            field=models.CharField(
                default="Using FISH / Shipment Prep Summary Request for PO_NUMBER",
                max_length=255,
            ),
        ),
    ]
